name: Handle info.xml merges

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

jobs:
  handle-info-xml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.base_ref }} # main branch
          fetch-depth: 0

      - name: Create merge driver script
        run: |
          echo '#!/bin/sh' > .git/keep-main
          echo 'cp "$2" "$1"' >> .git/keep-main
          chmod +x .git/keep-main

      - name: Configure Git to ignore info.xml
        run: |
          git config --local merge.ours.driver true
          echo "appinfo/info.xml merge=ours" >> .gitattributes
          git config --local merge.ours.name "always keep main version"
          git config --local merge.ours.driver "$(pwd)/.git/keep-main %A %O %B"

      - name: Auto-resolve info.xml conflicts
        run: |
          git checkout ${{ github.head_ref }}
          git checkout main -- appinfo/info.xml
          git add appinfo/info.xml
          git commit -m "Keep main's info.xml version" || echo "No changes needed"
          git push origin ${{ github.head_ref }}