name: Sync to Beta Branch

permissions:
  contents: write
  actions: write

on:
  push:
    branches:
      - development

jobs:
  sync-to-beta:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.sha }}  # Explicitly checkout the commit that triggered the workflow
          ssh-key: ${{ secrets.BETA_DEPLOY_KEY }}

      - name: Configure Git SSH
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git remote set-url origin git@github.com:${{ github.repository }}.git

      - name: Update beta branch
        run: |
          # Fetch all branches
          git fetch origin
          
          # Check if beta branch exists
          if git show-ref --quiet refs/remotes/origin/beta; then
            # If exists, checkout beta
            git checkout beta
            git reset --hard origin/development  # Reset to latest development state
          else
            # If doesn't exist, create from development
            git checkout -b beta origin/development
          fi
          
          # Push to beta branch using SSH with force
          git push -f origin beta